spring:
  application:
    name: butly

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/butly}
    username: ${SPRING_DATASOURCE_USERNAME:butly}
    password: ${SPRING_DATASOURCE_PASSWORD:appuser@123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}